### ISSUE TITLE
Request for working data download link

### ISSUE THREAD

**Issue by GenTxt** [spenteco/nanogenmo2018#1]
Hello:

Thanks for this repo. I have everything working using my own data files and I would like to experiment with the scifi corpus offered but the link isn't working.

https://robineggsky.com/scifi.tar.gz

Cheers and Happy New Year.

**Comment by spenteco** [comment]
I'll have a look for it this evening, when I'm back home . . .

**Comment by spenteco** [comment]
Fixed.

Apologies for the delay . . .

**Comment by GenTxt** [comment]
Thanks. Downloading now.

Happy New Year
